### ISSUE TITLE
External radio atennas

### ISSUE THREAD

**Issue by colinsauze** [abersailbot/dewi-hardware#18]
External antennas for Xbee, Wifi and RC. If on same frequency (e.g. 2.4 ghz) antennas should be at different heights to avoid interference.

**Comment by TomGC96** [comment]
One external antenna has been mounted on the deck for WiFi.

**Comment by TomGC96** [comment]
2 external antennae have been attached to the deck, using Bulgin 400 Series Miniature Connectors. These have drastically increased our range for both XBee and WiFi.
