### ISSUE TITLE
PCB on Pi

### ISSUE THREAD

**Issue by colinsauze** [abersailbot/dewi-hardware#21]
Put the AtMega and power distribution, possibly regulator on PCB that fits ontop of Pi.

**Comment by naturesyouth** [comment]
At least part of this is being integrated on the mounting solution for #45

**Comment by naturesyouth** [comment]
See abersailbot/dewi-hardware/pull/49

**Comment by naturesyouth** [comment]
Version 1 has already be deployed at sailbot, and version 1.2 will be fabbed over summer for WRSC

**Comment by Danyc0** [comment]
This should be closed when the PCB has been tested and is 100% working in fabbed state, with no extra jumper wires, etc. Think "done done".

**Comment by naturesyouth** [comment]
This issue was moved to abersailbot/captain-h-morgan#1
