### ISSUE TITLE
Fix back of keel properly.

### ISSUE THREAD

**Issue by colinsauze** [abersailbot/dewi-hardware#29]
Insert a metal rod into keel to reinforce it.

**Comment by naturesyouth** [comment]
Fixed with epoxy putty but not reinforced

**Comment by thip** [comment]
It will just break again... it needs the reinforcement

**Comment by TomGC96** [comment]
Back of keel has been repaired with a mixture of epoxy, microfibres and colloidal silica. It has been sanded down but will need to be re-painted.

**Comment by Danyc0** [comment]
This should probs get closed when the re-painting gets finished, so that it's "done done"

**Comment by TomGC96** [comment]
I'll open another issue, seeing as this specific task has been completed.
