### ISSUE TITLE
Better handles.

### ISSUE THREAD

**Issue by colinsauze** [abersailbot/dewi-hardware#30]
Try to improve handles so they are more comfortable and larger. Front handle is structural for the jib to deck connection.

**Comment by TomGC96** [comment]
Since the front handle has broken off it will need to be fully replaced or removed. Currently the front block has been screwed to the deck and an eyelet has been attached to connect the jib boom.

**Comment by TomGC96** [comment]
The front handle has now been fully replaced with a stainless steel eye plate screwed in with stainless steel screws and sealed with silicone. This allows the jib to be tied down, as well as allowing us to use a rope handle which can be detached when necessary. It has been tested and found to be working satisfactorily, though the rope handle could be made a little more comfortable by surrounding it with PVC tubing. This closes the issue for the time being, but it can be re-opened if it is found to be unsuitable.
