### ISSUE TITLE
Underclock Pi

### ISSUE THREAD

**Issue by colinsauze** [abersailbot/dewi-hardware#36]
Reduce clock speed to reduce power consumption.

**Comment by kragniz** [comment]
It would be interesting to benchmark this to see how much power saving we could get here.

**Comment by TomGC96** [comment]
Given the time we have seen the computers run on one charge (Long Distance race at Sailbot in Annapolis) I believe this can be closed. With plans to use computers for vision this will also most likely prove to be impractical. If we find battery life to become an issue we can re-open.
