### ISSUE TITLE
Fix Pi/Arduino mounting inside main electronics/'Computers' box

### ISSUE THREAD

**Issue by Danyc0** [abersailbot/dewi-hardware#45]
Fix the Pi/Arduino mounting inside main electronics/'Computers' box. At the moment it's built of an old drinks bottle i think, which is causing the pi to get rather hot

**Comment by naturesyouth** [comment]
started working on an interface board

**Comment by naturesyouth** [comment]
See abersailbot/dewi-hardware/pull/49

**Comment by Tebazil12** [comment]
Can this issue be closed now?

**Comment by Danyc0** [comment]
@naturesyouth @Tebazil12: Is this closable?
