### ISSUE TITLE
Alternative methods of Arduino programing

### ISSUE THREAD

**Issue by naturesyouth** [abersailbot/dewi-hardware#48]
It would be nice if someone could look into the possibility of programming the Arduino without a usb connection, either over spi or serial, preferably with some hardware experimentation. This is in refrence to #45

**Comment by Danyc0** [comment]
So this page explains how to program an arduino using another arduino:
https://www.arduino.cc/en/Tutorial/ArduinoISP
I reckon if you reimplemented the ArduinoISP example (found built into the IDE these days) for the Pi it might just be possible. However I think that would take too much time to be worth it just for the purpose of getting rid of a USB cable

**Comment by naturesyouth** [comment]
This issue was moved to abersailbot/captain-h-morgan#4
