### ISSUE TITLE
New Stand

### ISSUE THREAD

**Issue by colinsauze** [abersailbot/dewi-hardware#5]
Make a new stand that is:
1. collapsable 
2. lightweight
3. has two wheels

**Comment by naturesyouth** [comment]
and go faster flames

**Comment by Tebazil12** [comment]
Fixed old stand

**Comment by TomGC96** [comment]
Have created a new portable stand for Dewi, however may need some adjusting and requires attaching side beams.

**Comment by TomGC96** [comment]
New portable stand has been sanded to fit and side beams have been attached.
