### ISSUE TITLE
Diagnose rudder servo problem

### ISSUE THREAD

**Issue by kragniz** [abersailbot/dewi-hardware#72]
The rudder servo stopped being powered after test. Figure out what's wrong with it.

**Comment by Danyc0** [comment]
By the sounds of what was described, it's either that the gearing has jammed, or the motor has burnt out. I'd say the former is more likely because the photo's show nothing obvious.

**Comment by TomGC96** [comment]
The servo has been removed and is broken. It appears that the motor may have burnt out, judging by the smell and the fact that it takes 3 amps by powering it directly from a power supply. A replacement identical servo has been ordered, and will arrive and be fitted soon.

**Comment by Danyc0** [comment]
Why order the exact same? Surely that means it might just do the same thing again?

**Comment by TomGC96** [comment]
Because now is not really the time to be making big modifications to the way the boat works, considering the competition is so soon. Additionally and maybe more importantly, we have no, and have had no suggestions for any alternatives.

**Comment by Tebazil12** [comment]
The last one survived 3+ years so that type is definitely good enough for now.

**Comment by CloudCoppola** [comment]
Diagnoses complete.
